schema_version = "1.0.0"
id = "voronoi_linker"
version = "5.6.9"
name = "Voronoi Linker"
tagline = "无敌高效"
maintainer = "ugorek;W_Cloud"
type = "add-on"
tags = ["Node"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/neliut/VoronoiLinker"
# website = "https://space.bilibili.com/1109241880"